### ISSUE TITLE
make master buildable

### ISSUE THREAD

**Issue by steakhal** [andreihu/asio-fsm#3]
`master` branch should be always in a buildable state

**Comment by andreihu** [comment]
Thanks for the report!

That's correct, it's time to try to reach some sort of alpha state and wrap up source code to be usable to the public.

As a short term plan (until alpha status is reached): 
 - Work shall be done on the master branch and reach a useful state asap.
 - When alpha status reached, develop branch shall be created and merge pull requests into develop first. Then merge&tag releases into master.
