### ISSUE TITLE
replacing `tfm` library dep with `fmt`

### ISSUE THREAD

**Issue by steakhal** [andreihu/asio-fsm#4]
`fmt` becomes part of modern c++, probably good idea moving towards it.

**Comment by andreihu** [comment]
I am not familiar with {fmt}, but i'd be happy to migrate asio-fsm to it, since it seems to be more mature than tinyformat.

**Comment by steakhal** [comment]
Today I'm gonna create a PR with the necessary modifications. Though I don't like create changes which I cannot check if works - since master branch is broken currently.
